version: '3'
services:
  web:
    image: node
    container_name: web_medicina
    build: .
    restart: always
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    links:
      - mongo

  mongo:
    container_name: mongodatabase
    image: mongo
    ports:
      - 27018:27017
    logging:
      driver: none
